name: Calling Reusable Workflow
on: 
 workflow_dispatch: 
    inputs:
       name:
        description: 'Input description'
        type: string
        default: 'Ali'
        required: false 

jobs:
  calling-reusable-wf-in-same-repo:
    uses: ./.github/workflows/reusable-workflow.yaml
  using-reusable-workflow-output:
    runs-on: ubuntu-latest
    needs: calling-reusable-wf-in-same-repo
    steps:
      - run: echo "This is me"
    