name: Concurrency 1

on:
 workflow_dispatch:
    inputs:
        environment:
            description: "Environment"
            type: string
            default: staging
concurrency: 
  group: concurrency-1
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30            