name: Concurrency 1

on:
 workflow_dispatch:
    inputs:
      option:
        description: "Environment"
        type: choice
        required: true
        default: "Development"
        options:
            - QA
            - Staging
            - Production
concurrency: 
  group: concurrency-1
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30            