name: Dynamic Environment Variables
on: [push]
env:
 WF_LEVEL_ENV: This is available to all jobs and steps

jobs:
  env-vars-and-context:
    env:
     JOB_LEVEL_ENV: This is available to all steps for this job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
     - name: log ENV VAR
       run: echo $GITHUB_REF            
     - name: Log Context
       run: echo '${{ github.ref }}'  
     - name: Set ENV var
       run: | 
        echo "NEW_ENV_VAR=$(date)" >> "$GITHUB_ENV"
        echo "JOB_LEVEL_ENV=$RANDOM" >> "$GITHUB_ENV"
     - name: Multiline String
       run: | 
        DELIMITER=1234
        echo "RANDOM_JOKE  << $DELIMITER" >> "$GITHUB_ENV"
        echo "Here is a Joke: " >> "$GITHUB_ENV"
        curl -s https://icanhazdadjoke.com/ >> "$GITHUB_ENV"
        echo "" >> "$GITHUB_ENV"
        echo "$DELIMITER" >> "$GITHUB_ENV"
     - name: Log Custom Env Vars
       env: 
        STEP_LEVEL_ENV: Available to this steps only
        WF_LEVEL_ENV: overriden in steps
       run: | 
        echo '${{ env.STEP_LEVEL_ENV }}'
        echo $STEP_LEVEL_ENV
        echo $WF_LEVEL_ENV
        echo $JOB_LEVEL_ENV
        echo $NEW_ENV_VAR
        echo $RANDOM_JOKE

