name: pull request comment

on:
    pull_request_target:
        types: [ opened ]
jobs:
    pr-comment:
        runs-on: ubuntu-latest
        steps:
            - name: commeent on new pr
              uses: actions/github-script@v6
              with:
                script: |
                  github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: 'Thanks for contributing!',
                  });        