name: status check function

on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: sleep 20
      - name: Runs on Failure
        if: failure()
        run: echo 'Runs on Failure'
      - name: Runs On Success
        if: success()
        run: echo 'Runs On Success'
      - name: Always Run
        if: always()
        run: echo 'Always Run'
      - name: Runs When Cancelled
        if: cancelled() 
        run: echo 'Runs On Cancelled'      
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
     - run: echo 'Job-2'
            