name: Workflow run

on:
  workflow_run:
    workflows: [ Events-types ]
    types:
        - completed
jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "I was triggred because 'ebvets' workflow completed"        
